/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csrportal.views;

import csrportal.CSRPortal;
import csrportal.helpers.AppProperties;
import csrportal.helpers.DB;

/**
 *
 * @author shady
 */
public class StartUpForm extends javax.swing.JDialog {

    /**
     * Creates new form StartUpForm
     */
    
    public StartUpForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        appInit();
    }
    
    public void appInit(){
        this.createTables();
        this.setAppAsLoaded();
    }
    
    public void setAppAsLoaded(){
        AppProperties prop = new AppProperties();
        prop.setIsAppLoaded("true");
        prop.save();
    }
    
    public void createTables(){
        Thread createDb;
        createDb = new Thread() {
            @Override
            public void run() {
                DB db = new DB();
                db.createTable(createAppointments());
                db.createTable(createMessages());
                db.createTable(createNotes());
                db.createTable(createVisitors());
                System.out.println("tables created");
                openApp();
                
            };
        };
        createDb.start();
    }
    
    public String createAppointments(){
        String sql ="CREATE TABLE IF NOT EXISTS \"Appointments\" (\n" +
        "`id` INTEGER PRIMARY KEY AUTOINCREMENT,\n" +
        "`app_date` TEXT,\n" +
        "`app_time` TEXT,\n" +
        "`app_person` TEXT,\n" +
        "`app_meeting` TEXT,\n" +
        "`contact_email` TEXT,\n" +
        "`contact_phone` TEXT,\n" +
        "`reason` TEXT\n" +")";
        return sql;
    }
    
    public String createMessages(){
        String sql = "CREATE TABLE IF NOT EXISTS `Messages` (\n" +
        "`id` INTEGER PRIMARY KEY AUTOINCREMENT,\n" +
        "`message_for` TEXT,\n" +
        "`note` TEXT,\n" +
        "`message_date` TEXT,\n" +
        "`message_time` TEXT\n" +")";
        return sql;
    }
    
    public String createNotes(){
        String sql = "CREATE TABLE IF NOT EXISTS `Notes` (\n" +
        "`id` INTEGER PRIMARY KEY AUTOINCREMENT,\n" +
        "`note` TEXT,\n" +
        "`note_date` TEXT,\n" +
        "`note_time` TEXT,\n" +
        "`tags`	TEXT\n" +")";
        return sql;
    }
    
    public String createVisitors(){
        String sql = "CREATE TABLE IF NOT EXISTS \"Visitors\" (\n" +
        "`visitor_id` INTEGER PRIMARY KEY AUTOINCREMENT,\n" +
        "`first_name` TEXT,\n" +
        "`last_name` TEXT,\n" +
        "`mailing_address` TEXT,\n" +
        "`address` TEXT,\n" +
        "`primary_contact` TEXT,\n" +
        "`secondary_contact` TEXT,\n" +
        "`reason` TEXT,\n" +
        "`visit_date` TEXT,\n" +
        "`visit_time` TEXT,\n" +
        "`attending_person` TEXT,\n" +
        "`email` TEXT\n" +")";
        return sql;
    }
    
    public void openApp(){
        HomeFrame mainApp = new HomeFrame();
        mainApp.setLocationRelativeTo(null);
        mainApp.setVisible(true);
        mainApp.setTitle("CSR Portal");
        setVisible(false);
    }
        
    
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Loading Settings of app");

        jToggleButton1.setText("jToggleButton1");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jToggleButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jToggleButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        CSRPortal csp = new CSRPortal();
        this.setVisible(false);
        csp.startApp();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                StartUpForm dialog = new StartUpForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
